version: 2.1
jobs:
  build-debian:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: GOBIN=/go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}} make
      - run: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/may -v
  build-arch:
    docker:
      - image: archlinux
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - run: pacman -Syu --noconfirm
      - run: pacman -S go make --noconfirm
      - checkout
      - run: go get -v -t -d ./...
      - run: GOBIN=/go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}} make
      - run: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/may -v
  integrationtest-debian:
    machine: true
    steps:
      - checkout
      - run:
          name: Build & Run Integrationtest
          command: | 
            make integrationtest-debian
  integrationtest-arch:
    machine: true
    steps:
      - checkout
      - run:
          name: Build & Run Integrationtest
          command: | 
            make integrationtest-arch
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build-debian
      - build-arch
      - integrationtest-debian:
          requires:
            - build-debian
      - integrationtest-arch:
          requires:
            - build-arch

