version: 2.1
orbs:
  golang: cci-orb/golang@0.1.8
jobs:
  build-debian:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: GOBIN=/go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}} make
      - run: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/may
  build-arch:
    docker:
      - image: archlinux
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - run: pacman -Syu
      - run: pacman -S go
      - checkout
      - run: go get -v -t -d ./...
      - run: GOBIN=/go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}} make
      - run: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/may
  benchmark:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: make release
      - run: 
          name: Execute basic benchmark
          command: |
            sudo apt-get install -y multitime && make benchmark
  integrationtest:
    machine: true
    steps:
      - checkout
      - run:
          name: Build test environment
          command: | 
            docker build -f test.Dockerfile -t maytest .
      - run:
          name: Execute test
          command: docker run maytest
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build-debian
      - build-arch
      - integrationtest:
          requires:
            - build-debian
            - build-arch
      - benchmark:
          requires:
            - integrationtest

