version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: make
  benchmark:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: make release
      - run: 
          name: Execute basic benchmark
          command: |
            sudo apt-get install -y multitime && make benchmark
  integrationtest:
    machine: true
    steps:
      - checkout
      - run:
          name: Build test environment
          command: | 
            docker build -f test.Dockerfile -t maytest .
      - run:
          name: Execute test
          command: docker run maytest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - integrationtest:
          requires:
            - build
      - benchmark:
          requires:
            - integrationtest

