version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: make
      - run: sudo apt-get install -y multitime && make benchmark
  integrationtest:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
      - run: sudo apt-get install docker-ce docker-ce-cli containerd.io
      - run: docker build -f test.Dockerfile -t maytest .
      - run: docker run maytest
