version: 2
orbs:
  golang: cci-orb/golang@0.1.8
jobs:
  build-debian:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: GOBIN=. make
      - run: ./may
  build-macos:
    executor: golang/macos
    steps:
      - checkout
      - run go get -v -t -d ./...
      - run: GOBIN=. make
      - run: ./may
  benchmark:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: make release
      - run: 
          name: Execute basic benchmark
          command: |
            sudo apt-get install -y multitime && make benchmark
  integrationtest:
    machine: true
    steps:
      - checkout
      - run:
          name: Build test environment
          command: | 
            docker build -f test.Dockerfile -t maytest .
      - run:
          name: Execute test
          command: docker run maytest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build-debian
      - build-macos
      - integrationtest:
          requires:
            - build-debian
      - benchmark:
          requires:
            - integrationtest

